chroma = require("chroma-js");
out = process.stdout;

const wheel = (steps, s, v, space) => {
  // return Array.from({ length: steps }, (_, i) => scale(i / steps).hex());
  return Array.from(
    { length: steps },
    (_, i) => {
      h = 360 * i / steps;
      // return [h, chroma.lch(48, 134, h).rgb()];
      // return [chroma.oklch(0.48, 0.2, h).hex(), h];
      // return chroma(l, c, h, space).rgb();
      return chroma(h, s, v, space).rgb();
    },
  );
};

const print = (steps) => {
  // color_space = "oklch";
  // l = 0.48;
  // c = 0.2;
  // color_space = "lch";
  // l = 15;
  // c = 150;
  color_space = "hsv";
  s = 1;
  v = 1;
  arr = wheel(steps, s, v, color_space);
  out.write(
    "// " + arr.length + " colors, generated by `node chroma/wheel.js`\n",
  );
  out.write(
    "// " + "color_space=" + color_space + ", v=" + v + ", s=" + s + "\n",
  );
  out.write("uint8_t color_wheel_max_idx = " + (arr.length - 1) + ";\n");
  out.write("uint8_t color_wheel[][3] = {\n");
  arr.forEach((rgb) => {
    out.write("    { ");
    rgb.forEach((comp) => {
      out.write(comp + ", ");
    });
    out.write("},\n");
  });
  out.write("};\n");
};

print(180);
